{
 "title": "FTP-Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Read: sdb",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_disk_read_bytes_total{device=\"sdb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Write: sdb",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_disk_written_bytes_total{device=\"sdb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free: sdb",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_btrfs_device_unused_bytes{device=\"sdb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used: metadata",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_btrfs_used_bytes{block_group_type=\"metadata\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used: data",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_btrfs_used_bytes{block_group_type=\"data\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used: system",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_btrfs_used_bytes{block_group_type=\"system\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free: sda",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_btrfs_device_unused_bytes{device=\"sda\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Write: sda",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_disk_written_bytes_total{device=\"sda\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Read: sda",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_disk_read_bytes_total{device=\"sda\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Generation-Err: sdb",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_btrfs_device_errors_total{device=\"sdb\", type=\"generation\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flush-Err: sdb",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 1, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_btrfs_device_errors_total{device=\"sdb\", type=\"flush\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Corruption-Err: sdb",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_btrfs_device_errors_total{device=\"sdb\", type=\"corruption\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read-Err: sdb",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_btrfs_device_errors_total{device=\"sdb\", type=\"read\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write-Err: sdb",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_btrfs_device_errors_total{device=\"sdb\", type=\"write\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free SD-Card",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device=\"/dev/root\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write-Err: sda",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_btrfs_device_errors_total{device=\"sda\", type=\"write\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read-Err: sda",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_btrfs_device_errors_total{device=\"sda\", type=\"read\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Corruption-Err: sda",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_btrfs_device_errors_total{device=\"sda\", type=\"corruption\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flush-Err: sda",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 22, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_btrfs_device_errors_total{device=\"sda\", type=\"flush\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Generation-Err: sda",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 23, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_btrfs_device_errors_total{device=\"sda\", type=\"generation\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write: sdb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"sdb\", job=\"node_exporter\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Core 0",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{mode=\"idle\", cpu=\"0\"}[1m]) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Core 1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{mode=\"idle\", cpu=\"1\"}[1m]) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Core 2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{mode=\"idle\", cpu=\"2\"}[1m]) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Core 3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{mode=\"idle\", cpu=\"3\"}[1m]) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write: sda",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"sda\", job=\"node_exporter\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "__auto" },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Read: sdb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"sdb\", job=\"node_exporter\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read: sda",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"sda\", job=\"node_exporter\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write: SD-Card",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"mmcblk0\", job=\"node_exporter\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read: SD-Card",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"mmcblk0\", job=\"node_exporter\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}