{
 "title": "Host-and-Raid-Monitoring-Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_filesystem_free_bytes", "legendFormat": "{{device}}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "node_hwmon_temp_celsius", "legendFormat": "{{chip}} {{sensor}}" }
   ]
  },
  {
   "title": "Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_filesystem_free_bytes", "legendFormat": "Free {{device}}" }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Total" },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Available" }
   ]
  },
  {
   "title": "Read",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 11, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{mode=\"idle\"}[1m]) * 100)",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "Write",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "zpool dataset reads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "expr": "node_zfs_zpool_dataset_reads", "legendFormat": "{{dataset}} reads" },
    { "expr": "node_zfs_zpool_dataset_nread", "legendFormat": "{{dataset}} nread" }
   ]
  },
  {
   "title": "zpool dataset writes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "expr": "node_zfs_zpool_dataset_writes", "legendFormat": "{{dataset}} writes" },
    {
     "expr": "node_zfs_zpool_dataset_nwritten",
     "legendFormat": "{{dataset}} nwritten"
    }
   ]
  },
  {
   "title": "zil zil commit",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "node_zfs_zil_zil_commit_count", "legendFormat": "{{__name__}}" },
    {
     "expr": "node_zfs_zil_zil_commit_error_count",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "node_zfs_zil_zil_commit_stall_count",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "node_zfs_zil_zil_commit_suspend_count",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "node_zfs_zil_zil_commit_writer_count",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "zil dataset commit",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "node_zfs_zpool_dataset_zil_commit_count",
     "legendFormat": "{{dataset}} {{__name__}}"
    },
    {
     "expr": "node_zfs_zpool_dataset_zil_commit_error_count",
     "legendFormat": "{{dataset}} {{__name__}}"
    },
    {
     "expr": "node_zfs_zpool_dataset_zil_commit_stall_count",
     "legendFormat": "{{dataset}} {{__name__}}"
    },
    {
     "expr": "node_zfs_zpool_dataset_zil_commit_suspend_count",
     "legendFormat": "{{dataset}} {{__name__}}"
    },
    {
     "expr": "node_zfs_zpool_dataset_zil_commit_writer_count",
     "legendFormat": "{{dataset}} {{__name__}}"
    }
   ]
  },
  {
   "title": "zpool state",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "targets": [
    { "expr": "node_zfs_zpool_state", "legendFormat": "{{zpool}} {{state}}" }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {}
   ]
  }
 ]
}