{
 "title": "Host-and-Raid-Monitoring-Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Used Storage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_btrfs_used_bytes{block_group_type=\"data\"}",
     "legendFormat": "Data"
    },
    {
     "expr": "node_btrfs_used_bytes{block_group_type=\"metadata\"}",
     "legendFormat": "Metadata"
    },
    {
     "expr": "node_btrfs_used_bytes{block_group_type=\"system\"}",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Commit Info",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_btrfs_max_commit_seconds", "legendFormat": "Slowest" },
    { "expr": "node_btrfs_last_commit_seconds", "legendFormat": "Last" },
    { "expr": "node_btrfs_commits_total", "legendFormat": "Total" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device=\"/dev/root\"}",
     "legendFormat": "Free {{device}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "node_hwmon_temp_celsius", "legendFormat": "Sensor {{sensor}}" }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_btrfs_device_size_bytes", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Free Storage",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_btrfs_device_unused_bytes", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Write",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Read",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Total" },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Available" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{mode=\"idle\"}[1m]) * 100)",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "Raid Error",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_btrfs_device_errors_total[$__rate_interval])",
     "legendFormat": "{{device}}: {{type}}"
    }
   ]
  }
 ]
}