{
 "title": "Host-and-Raid-Monitoring-Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "RaidDevice",
    "query": {
     "query": "label_values(node_btrfs_device_size_bytes,device)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_btrfs_used_bytes", "legendFormat": "{{mode}}-{{block_group_type}}" }
   ]
  },
  {
   "title": "Read: sdb",
   "type": "stat",
   "gridPos": { "h": 24, "w": 6, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[1m])",
     "legendFormat": "Read {{device}}"
    },
    {
     "expr": "rate(node_disk_written_bytes_total[1m])",
     "legendFormat": "Write {{device}}"
    }
   ]
  },
  {
   "title": "Free Intern ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device=\"/dev/root\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "node_hwmon_temp_celsius", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "__auto" },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Raid Error",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_btrfs_device_errors_total", "legendFormat": "{{device}}-{{type}}" },
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "node_btrfs_max_commit_seconds", "legendFormat": "Duration of the slowest commit" },
    {
     "expr": "node_btrfs_last_commit_seconds",
     "legendFormat": "Duration of the most recent commit"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{mode=\"idle\"}[1m]) * 100)",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_btrfs_device_size_bytes", "legendFormat": "{{device}}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_btrfs_device_unused_bytes", "legendFormat": "Free {{device}}" }
   ]
  }
 ]
}